---
- hosts: localhost
  tasks:
    - name: download nomad
      get_url: url=https://releases.hashicorp.com/nomad/0.8.4/nomad_0.8.4_linux_amd64.zip dest=/tmp/nomad_0.8.4_linux_amd64.zip
  
    - name: install unzip
      apt: name=unzip state=installed
      when: ansible_os_family == "Debian"

    - name: unzip nomad
      unarchive:
        src: /tmp/nomad_0.8.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: create proper directories
      file: path={{ item }} state=directory mode=0755
      with_items:
        - /etc/nomad.d/
    
    - name: install supervisor
      apt: name=supervisor state=installed

    - name: upload nomad supervisord script
      copy: src=nomad.conf dest=/etc/supervisor/conf.d/nomad.conf

    - name: load nomad with supervisord
      shell: "{{ item }}"
      with_items:
        - supervisorctl reread
        - supervisorctl update
